source 'http://rubygems.org'

# gem 'rails', '3.1.0' #no longer supporting security updates
gem 'rails', '3.2.15'

# Bundle edge Rails instead:
# gem 'rails',     :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  #gem 'coffee-rails', "~> 3.1.0"
  gem 'uglifier'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer'

end

gem 'jquery-rails'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
gem 'debugger'

group :test do
  # Pretty printed test output
  gem 'turn', :require => false
end

gem 'rinruby'

gem 'rubyzip'
